# Generated by Django 5.2 on 2025-05-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='employer',
            new_name='user',
        ),
    ]
