# Generated by Django 5.2 on 2025-05-06 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted')], default='submitted', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('applicant', 'job_post')},
        ),
    ]
