# Generated by Django 5.2 on 2025-05-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
