# Generated by Django 5.2 on 2025-05-06 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_jobapplication_status'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPosting',
            new_name='JobPost',
        ),
    ]
